apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
    name: sykdom-i-familien
    namespace: dusseldorf
    labels:
        team: dusseldorf
spec:
    image: {{ image }}
    port: 8080
    liveness:
        path: /familie/sykdom-i-familien/isalive.txt
        initialDelay: 20
        timeout: 1
        periodSeconds: 5
        failureThreshold: 10
    readiness:
        path: /familie/sykdom-i-familien/isready.txt
        initialDelay: 20
        timeout: 1
    resources:
        limits:
            cpu: 2000m
            memory: 512Mi
        requests:
            cpu: 50m
            memory: 128Mi
    accessPolicy:
        outbound:
            external:
            - host: www.nav.no
    ingresses:
      {{#each ingresses as |url|}}
       - {{url}}
          {{/each}}
    replicas:
        min: 1
        max: 1
        cpuThresholdPercentage: 90
    prometheus:
        enabled: true
        path: /metrics
    vault:
        enabled: false
